# Project overrides
# Needed to avoid these errors:
# ../test/test26.cxx:47:21: error: 'value' is unavailable: introduced in macOS 10.13
# include/pqxx/blob.hxx:242:60: error: 'path' is unavailable: introduced in macOS 10.15

macos_min_version:             # [osx and x86_64]
  - 10.15                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.15                      # [osx and x86_64]

c_compiler:
  - vs2019                     # [win]
cxx_compiler:
  - vs2019                     # [win]

