{% set name = "libpqxx" %}
{% set version = "7.10.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jtv/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c5ba455e4f28901297c18a76e533c466cbe8908d4b2ff6313235954bb37cef25

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libpq
  run:

test:
  commands:
    - test -f ${PREFIX}/include/pqxx/pqxx               # [unix]
    - test -f ${PREFIX}/lib/libpqxx${SHLIB_EXT}         # [unix]
    - if not exist %LIBRARY_INC%\pqxx\pqxx (exit 1)     # [win]
    - if not exist %LIBRARY_LIB%\pqxx.lib (exit 1)      # [win]
    - if not exist %LIBRARY_BIN%\pqxx.dll (exit 1)      # [win]

about:
  home: https://github.com/jtv/libpqxx
  license: BSD-3-Clause
  license_file: COPYING
  summary: Welcome to libpqxx, the C++ API to the PostgreSQL database management system.

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - eunos-1128
