{% set name = "libpqxx" %}
{% set version = "7.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jtv/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2d99de960aa3016915bc69326b369fcee04425e57fbe9dad48dd3fa6203879fb

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
    - libpq
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/pqxx/pqxx               # [unix]
    - test -f ${PREFIX}/lib/libpqxx${SHLIB_EXT}         # [unix]
    - if not exist %LIBRARY_INC%\pqxx\pqxx (exit 1)     # [win]
    - if not exist %LIBRARY_LIB%\pqxx.lib (exit 1)      # [win]
    - if not exist %LIBRARY_BIN%\pqxx.dll (exit 1)      # [win]

about:
  home: https://github.com/jtv/libpqxx
  license: BSD-3-Clause
  license_file: COPYING
  summary: Welcome to libpqxx, the C++ API to the PostgreSQL database management system.

extra:
  recipe-maintainers:
    - Tobias-Fischer
